name: Build Wheels

on:
  push:
    tags:
      - '*'

env:
  CIBW_SKIP: pp* *-win32 *-manylinux_i686 *-musllinux*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: ubuntu
            arch: x86_64
            runner: ubuntu-24.04
          - os: ubuntu
            arch: aarch64
            runner: ubuntu-24.04-arm64
          - os: windows
            arch: x86_64
            runner: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: joerick/cibuildwheel@v3.2.0
        env:
          CIBW_ARCHS_LINUX: ${{ matrix.arch }}
          CIBW_ARCHS_MACOS: "x86_64 arm64"
          CIBW_BEFORE_BUILD: pip install -U pip setuptools wheel cython numpy

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: built-wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
          if-no-files-found: warn
